apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  namespace: Sidhu-namespaces
spec:
  containers:
   - name: nginx-con
     image: nginx
     envFrom:
        - configMapRef:
            name: nginx-config