apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: Sidhu-namespaces
spec:
  containers:
  - name: app-nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"