apiVersion: v1
kind: Pod
metadata:
  name: node-ip-svc
  namespace: Sidhu-namespaces
  labels: 
   project: service-sidhu
   module: be
   environment: dev
spec:
  containers:
  - name: app-nginx-nodeport
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1 
kind: service
metadata:
 name: Sidhu-nodeport
 namespace: Sidhu-namespaces
 
spec:
 type: NodePort
 selector:
    project: service-sidhu
    module: be
    environment: dev
    containers:
    - name: nginx
      image: nginx:stable
      ports:
      - name: nginx-service-cip-port
        containerPort: 80
        targetPort: 80
        nodePort: 30013